name: 'Issue Compliance Action'
description: >
  Action to check issues for compliance on the title and required body infos
# branding:
#   icon: git-pull-request
#   color: green
# author: 'Matthew Foley'
inputs:
  token:
    required: false
    description: Github token
    default: ${{ github.token }}
  base-comment:
    required: true
    description: >
      Preamble portion to have on any comments made by the action. Because multiple checks are run, the action may have multiple sections to any generated comment.
    default: >
      # Issue Compliance Checks :clipboard:

      Thank you for opening this issue! We have run several checks on this issue in order
      to make sure it compliant with our contributing guidelines. Please review the checks
      below and make any necessary changes to this issue. Once all checks have passed, we
      will be able to triage this issue and take the next steps.
  issue-template-types:
    required: true
    description: >
      The types of issue templates to check against. If the issue does not have one of these templates, the check will fail and the issue will be marked as invalid.
    default: |
      Feature Request
      Bug Report
      Question
  title-check-enable:
    required: true
    description: Whether or not to lint the issue title
    default: true
  title-comment:
    required: false
    description: Comment to leave on issue on failed check of the issue title
    default: >
      ## Issue Title Format :pencil2:

      In order for this issue to be considered for triage, the issue title must match the specification below:
  characters-to-exclude:
    required: false
    description: >
      Characters to exclude from the issue title. If the issue title contains any of these characters, the check will fail and the issue will be marked as invalid.
    default: |
      <
      >
      #
      &
outputs:
  # body-check:
  #   description: 'Result of match for PR Body against configured regex.'
  # branch-check:
  #   description: 'Result of check to ensure PR head is not protected branch.'
  title-check:
    description: Result of check to ensure the issue title is formatted correctly.

runs:
  using: 'node16'
  main: 'dist/index.js'
