name: 'Issue Compliance Action'
description: >
  Action to check issues for compliance on the title and required body infos

branding:
  icon: check-circle
  color: green
author: 'El Hadji Malick Seck'

inputs:
  token:
    required: false
    description: Github token
    default: ${{ github.token }}
  label:
    required: true
    description: Label to add to issue if it is invalid
    default: '🙅 invalid'
  forbidden-characters:
    required: false
    description: >
      Characters to forbid in the issue title. If the issue title contains any of these characters, the check will fail and the issue will be marked as invalid.
    default: ''
  base-comment:
    required: true
    description: >
      Preamble portion to have on any comments made by the action. Because multiple checks are run, the action may have multiple sections to any generated comment.
    default: >
      # Issue Compliance Checks

      Thank you for filling this issue! We have run several checks on this issue in order
      to make sure it compliant with our contributing guidelines. Please review the checks
      below and make any necessary changes to this issue. Once all checks have passed, we
      will be able to triage this issue and take the next steps.
  title-comment:
    required: true
    description: Comment to leave on issue on failed check of the issue title
    default: >
      ## Issue Title Format

      In order to be considered for triage, the issue title must match the specification below.
      Please update the title to match the specification in order for this check to pass.

outputs:
  title-check:
    description: Result of check to ensure the issue title is formatted correctly.

runs:
  using: 'node16'
  main: 'dist/index.js'
